In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import requests
# import gmaps
import os
# Import API key
from api_keys import g_key

In [13]:
data_set = 'data/Crew Data.csv'
input_data = pd.read_csv(data_set) 

input_data

,Pclass,Name,Survived,Sex,Age,Hometown,Role,Role Additional info,Image,Misc Information,Lifeboat,Body Disposition,Job Area,Source of info 1,Source of info 2
0,NaN,"Anderson, J.",1.0,male,40.0,Southampton,Able bodied seaman,NaN,NaN,NaN,NaN,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN
1,NaN,"Archer, Ernest",1.0,male,36.0,Southampton,Able bodied seaman,NaN,NaN,NaN,16,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN
2,NaN,"Bradley, F.",0.0,male,29.0,Southampton,Able bodied seaman,NaN,NaN,NaN,NaN,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN
3,NaN,"Brice, W.",1.0,male,42.0,Southampton,Able bodied seaman,NaN,NaN,NaN,11,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN
4,NaN,"Buley, Edward J.",1.0,male,27.0,Southampton,Able bodied seaman,NaN,NaN,NaN,10,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
914,NaN,"Williams, Jack",0.0,male,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN

In [3]:
Hometown = []
for row in input_data.index:
    name = input_data.at[row, 'Name']
    home = input_data.at[row, 'Hometown']
    Hometown.append(home)
Hometown_set = set(Hometown)
print(Hometown)
print(Hometown_set)

['Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Port Isaac, Cornwall', 'Portsmouth', 'Southampton', 'Southampton', nan, 'Southampton', 'Belfast', 'Southampton', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', nan, 'Cork, Ireland', 'Southampton', 'Southampton', 'Itchen, Hampshire', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', nan, 'Southampton', 'Southampton', 'Kingsworthy, Winchester', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Portsmouth', 'Swaything, Hampshire', 'Eastleigh', 'Plymouth', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'West Southbourne', 'London', 'Southampton', 'Bournemouth', 'Southampton', 'Southampton', 'Southampton', 'Belfast', 'Southampton', 'Southampton', 'Bitterne Park, Southampton', 'Belfast', 'Dublin, Ireland', 'Ballisare, Sligo', 'Southampton', 'Southampton', nan, 'Southampton', 'Southampton', 'Southampton', 'Winchester', 'New Southgate', 'Southampton', 'New Southgate', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Liverpool', 'London', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'Rue National-Ambroise, France', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Dolgelly', 'Bowerthalk, Salisbury', 'Salisbury', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Birkenhead', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Belfast Ireland', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'London', 'Southampton', 'London', 'London', 'London', 'London', 'London', 'Southampton', 'London', 'London', 'London', 'London', 'London', 'London', 'Southampton', 'Colne, Lancashire', 'Southampton', 'Southampton', 'London', nan, 'East Cowes', 'London', 'London', 'Southampton', 'Southampton', 'Southampton', 'Redland, Bristol', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Itchen, Hampshire', 'Eastleigh', 'Southampton', 'Southampton', 'Southampton', 'Illford, Essex', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Oxford', 'Southampton', 'Southampton', 'London', 'Little Sutton, Cheshire', nan, nan, nan, 'Southampton', 'London', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Itchen, Hampshire', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Southampton', 'Cheshire', 'Southampton', 'Crosby', 'Southampton', 'London', 'Emsworth', 'Southampton', 'Southampton', 'Woodside, Lymington', 'Southampton', 'Woolston, Hampshire', 'Southampton', nan, 'Southampton', 'Southampton', 'Southampton', 'Alloa, N. B.', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Eastleigh', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Belfast', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Gosport', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'E. Dulwich', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', nan, 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Belfast', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', nan, 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Northam', 'Lymington', 'London', 'Southampton', nan, 'London', 'Hull', 'Liverpool', 'Eastleigh', 'Portswood', 'Southampton', 'London', 'Southampton', 'Southampton', 'Belfast', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Highbury Hill', 'Southampton', 'Southampton', 'Southampton', 'Belfast', 'Southampton', 'London', 'Southampton', 'Romsey', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Belfast', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Bridgwood', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Northam, Hampshire', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Liverpool', 'Gateshead-On-Tyne', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Weymouth', 'Chandlersford, Hampshire', 'Southampton', 'Southampton', 'Great Yarmouth', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'London', nan, 'Southampton', 'Southampton', 'Liverpool', 'Southampton', 'London', 'Southampton', 'Christschurch, Hampshire', 'Southampton', 'Southampton', 'Southampton', 'Woolston, Hampshire', 'Southampton', nan, nan, nan, nan, nan, 'London', nan, 'Southampton', 'Clones', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Bitterne, Hampshire', 'Gosport', 'Southampton', 'London', 'Southampton', 'London', 'Alresford', 'Southampton', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'Brooklands, Shepperton', 'London', 'Southampton', 'London', 'Wokingham', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Shortland, Kent', 'Southampton', 'Southampton', 'Southampton', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Lewisham', 'Newport, Isle of Wight', 'Southampton', 'Southampton', 'Weymouth', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Ryde, Isle of Wight', 'Sholing, Hampshire', 'Southampton', 'Southampton', 'Harbor View', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Lewisham', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Woolston, Hampshire', 'Southampton', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Ashbrittle, Somerset', 'Southampton', 'Southampton', 'Southampton', 'Itchen, Hampshire', 'Southampton', 'Bristol', 'Reading', 'Southampton', 'Southampton', 'Southampton', 'Winchester', 'Southampton', 'Southampton', 'Redbridge, Hampshire', 'London', 'Southampton', 'Southampton', 'Southampton', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Totton, Hampshire', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'London', 'Woolston, Hampshire', 'Southampton', 'Southampton', 'Fareham', 'Southampton', 'Woolston, Hampshire', 'Liverpool', 'Southampton', 'Itchen, Hampshire', 'Belfast', nan, 'Southampton', 'Southampton', 'London', 'Woolston, Hampshire', 'Liverpool', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Stirling', 'Southampton', 'Southampton', 'Southampton', 'Grimsby', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southsea', 'Landport', 'Southampton', 'London', nan, 'Southampton', 'Southampton', 'Southampton', 'Totton, Hampshire', 'Southampton', 'London', 'Southampton', 'Southampton', 'Bishopstoke', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Bournemouth', 'Rockbourne', 'Pournemouth', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Paddington', 'Southampton', 'Southampton', 'Southampton', 'West Croydon', 'Southampton', 'Southampton', 'New Southgate', 'Southampton', 'Southampton', 'London', 'Winchester', 'Port Sunlight', 'Southampton', 'Portsmouth', 'Southampton', 'London', 'Notts', 'Southampton', 'Belfast', 'Southampton', 'Sandown', 'Birkenhead', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Northam, Hampshire', 'Southampton', 'Southampton', 'Soberton, Hampshire', 'Northants', 'Reading', 'Southampton', 'Southampton', 'Somerset', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Headbourne, W. F.', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', nan, 'Southampton', 'Southampton', 'Southampton', 'Woking', 'Southampton', 'Southampton', 'Southampton', 'London', 'London', 'Southport', 'London', 'Blackpool', 'Liverpool', 'Southampton', 'Southampton', nan, 'London', 'London', 'London', 'Southampton', 'Southampton', 'London', 'Southampton', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'Southampton', 'Southampton', 'Southampton', 'Southampton', 'Southampton', nan, nan, nan, nan, nan]
{nan, 'Crosby', 'Southsea', 'Soberton, Hampshire', 'East Cowes', 'Clones', 'Rue National-Ambroise, France', 'Lewisham', 'Hull', 'Wokingham', 'Belfast', 'Bitterne Park, Southampton', 'Bournemouth', 'Shortland, Kent', 'Woolston, Hampshire', 'Stirling', 'Sholing, Hampshire', 'Portsmouth', 'Southport', 'Reading', 'New Southgate', 'Northam', 'Gosport', 'Dublin, Ireland', 'Plymouth', 'Bridgwood', 'Sandown', 'Grimsby', 'Little Sutton, Cheshire', 'Totton, Hampshire', 'Pournemouth', 'Ryde, Isle of Wight', 'Rockbourne', 'Liverpool', 'Romsey', 'Woodside, Lymington', 'Newport, Isle of Wight', 'Headbourne, W. F.', 'Northam, Hampshire', 'Notts', 'Winchester', 'Somerset', 'London', 'Port Isaac, Cornwall', 'Harbor View', 'Landport', 'Redland, Bristol', 'Birkenhead', 'Paddington', 'Bowerthalk, Salisbury', 'Southampton', 'Lymington', 'Eastleigh', 'Bishopstoke', 'Alloa, N. B.', 'Swaything, Hampshire', 'West Southbourne', 'Portswood', 'Gateshead-On-Tyne', 'Ballisare, Sligo', 'Dolgelly', 'Northants', 'Oxford', 'E. Dulwich', 'Redbridge, Hampshire', 'Colne, Lancashire', 'Salisbury', 'Itchen, Hampshire', 'Bitterne, Hampshire', 'Christschurch, Hampshire', 'Cork, Ireland', 'Blackpool', 'Alresford', 'Bristol', 'Emsworth', 'Illford, Essex', 'West Croydon', 'Woking', 'Fareham', 'Cheshire', 'Belfast Ireland', 'Weymouth', 'Kingsworthy, Winchester', 'Chandlersford, Hampshire', 'Brooklands, Shepperton', 'Ashbrittle, Somerset', 'Port Sunlight', 'Great Yarmouth', 'Highbury Hill'}

In [10]:
finalList = []
cleanedList = [x for x in Hometown_set if str(x) != 'nan']
print(cleanedList)
for s in cleanedList:
    if "," in s:
        list = [s,s]
        finalList.append(list)
    else:
        new = s + ', UK'
        list = [s,new]
        finalList.append(list)
print(finalList)

['Crosby', 'Southsea', 'Soberton, Hampshire', 'East Cowes', 'Clones', 'Rue National-Ambroise, France', 'Lewisham', 'Hull', 'Wokingham', 'Belfast', 'Bitterne Park, Southampton', 'Bournemouth', 'Shortland, Kent', 'Woolston, Hampshire', 'Stirling', 'Sholing, Hampshire', 'Portsmouth', 'Southport', 'Reading', 'New Southgate', 'Northam', 'Gosport', 'Dublin, Ireland', 'Plymouth', 'Bridgwood', 'Sandown', 'Grimsby', 'Little Sutton, Cheshire', 'Totton, Hampshire', 'Pournemouth', 'Ryde, Isle of Wight', 'Rockbourne', 'Liverpool', 'Romsey', 'Woodside, Lymington', 'Newport, Isle of Wight', 'Headbourne, W. F.', 'Northam, Hampshire', 'Notts', 'Winchester', 'Somerset', 'London', 'Port Isaac, Cornwall', 'Harbor View', 'Landport', 'Redland, Bristol', 'Birkenhead', 'Paddington', 'Bowerthalk, Salisbury', 'Southampton', 'Lymington', 'Eastleigh', 'Bishopstoke', 'Alloa, N. B.', 'Swaything, Hampshire', 'West Southbourne', 'Portswood', 'Gateshead-On-Tyne', 'Ballisare, Sligo', 'Dolgelly', 'Northants', 'Oxford', 'E. Dulwich', 'Redbridge, Hampshire', 'Colne, Lancashire', 'Salisbury', 'Itchen, Hampshire', 'Bitterne, Hampshire', 'Christschurch, Hampshire', 'Cork, Ireland', 'Blackpool', 'Alresford', 'Bristol', 'Emsworth', 'Illford, Essex', 'West Croydon', 'Woking', 'Fareham', 'Cheshire', 'Belfast Ireland', 'Weymouth', 'Kingsworthy, Winchester', 'Chandlersford, Hampshire', 'Brooklands, Shepperton', 'Ashbrittle, Somerset', 'Port Sunlight', 'Great Yarmouth', 'Highbury Hill']
[['Crosby', 'Crosby, UK'], ['Southsea', 'Southsea, UK'], ['Soberton, Hampshire', 'Soberton, Hampshire'], ['East Cowes', 'East Cowes, UK'], ['Clones', 'Clones, UK'], ['Rue National-Ambroise, France', 'Rue National-Ambroise, France'], ['Lewisham', 'Lewisham, UK'], ['Hull', 'Hull, UK'], ['Wokingham', 'Wokingham, UK'], ['Belfast', 'Belfast, UK'], ['Bitterne Park, Southampton', 'Bitterne Park, Southampton'], ['Bournemouth', 'Bournemouth, UK'], ['Shortland, Kent', 'Shortland, Kent'], ['Woolston, Hampshire', 'Woolston, Hampshire'], ['Stirling', 'Stirling, UK'], ['Sholing, Hampshire', 'Sholing, Hampshire'], ['Portsmouth', 'Portsmouth, UK'], ['Southport', 'Southport, UK'], ['Reading', 'Reading, UK'], ['New Southgate', 'New Southgate, UK'], ['Northam', 'Northam, UK'], ['Gosport', 'Gosport, UK'], ['Dublin, Ireland', 'Dublin, Ireland'], ['Plymouth', 'Plymouth, UK'], ['Bridgwood', 'Bridgwood, UK'], ['Sandown', 'Sandown, UK'], ['Grimsby', 'Grimsby, UK'], ['Little Sutton, Cheshire', 'Little Sutton, Cheshire'], ['Totton, Hampshire', 'Totton, Hampshire'], ['Pournemouth', 'Pournemouth, UK'], ['Ryde, Isle of Wight', 'Ryde, Isle of Wight'], ['Rockbourne', 'Rockbourne, UK'], ['Liverpool', 'Liverpool, UK'], ['Romsey', 'Romsey, UK'], ['Woodside, Lymington', 'Woodside, Lymington'], ['Newport, Isle of Wight', 'Newport, Isle of Wight'], ['Headbourne, W. F.', 'Headbourne, W. F.'], ['Northam, Hampshire', 'Northam, Hampshire'], ['Notts', 'Notts, UK'], ['Winchester', 'Winchester, UK'], ['Somerset', 'Somerset, UK'], ['London', 'London, UK'], ['Port Isaac, Cornwall', 'Port Isaac, Cornwall'], ['Harbor View', 'Harbor View, UK'], ['Landport', 'Landport, UK'], ['Redland, Bristol', 'Redland, Bristol'], ['Birkenhead', 'Birkenhead, UK'], ['Paddington', 'Paddington, UK'], ['Bowerthalk, Salisbury', 'Bowerthalk, Salisbury'], ['Southampton', 'Southampton, UK'], ['Lymington', 'Lymington, UK'], ['Eastleigh', 'Eastleigh, UK'], ['Bishopstoke', 'Bishopstoke, UK'], ['Alloa, N. B.', 'Alloa, N. B.'], ['Swaything, Hampshire', 'Swaything, Hampshire'], ['West Southbourne', 'West Southbourne, UK'], ['Portswood', 'Portswood, UK'], ['Gateshead-On-Tyne', 'Gateshead-On-Tyne, UK'], ['Ballisare, Sligo', 'Ballisare, Sligo'], ['Dolgelly', 'Dolgelly, UK'], ['Northants', 'Northants, UK'], ['Oxford', 'Oxford, UK'], ['E. Dulwich', 'E. Dulwich, UK'], ['Redbridge, Hampshire', 'Redbridge, Hampshire'], ['Colne, Lancashire', 'Colne, Lancashire'], ['Salisbury', 'Salisbury, UK'], ['Itchen, Hampshire', 'Itchen, Hampshire'], ['Bitterne, Hampshire', 'Bitterne, Hampshire'], ['Christschurch, Hampshire', 'Christschurch, Hampshire'], ['Cork, Ireland', 'Cork, Ireland'], ['Blackpool', 'Blackpool, UK'], ['Alresford', 'Alresford, UK'], ['Bristol', 'Bristol, UK'], ['Emsworth', 'Emsworth, UK'], ['Illford, Essex', 'Illford, Essex'], ['West Croydon', 'West Croydon, UK'], ['Woking', 'Woking, UK'], ['Fareham', 'Fareham, UK'], ['Cheshire', 'Cheshire, UK'], ['Belfast Ireland', 'Belfast Ireland, UK'], ['Weymouth', 'Weymouth, UK'], ['Kingsworthy, Winchester', 'Kingsworthy, Winchester'], ['Chandlersford, Hampshire', 'Chandlersford, Hampshire'], ['Brooklands, Shepperton', 'Brooklands, Shepperton'], ['Ashbrittle, Somerset', 'Ashbrittle, Somerset'], ['Port Sunlight', 'Port Sunlight, UK'], ['Great Yarmouth', 'Great Yarmouth, UK'], ['Highbury Hill', 'Highbury Hill, UK']]

In [11]:
output = []
url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"

for home in finalList:
    print(f'Retrieving Results for Home | {home[1]}') 
    
    parameter = (f"input={home[1]}&inputtype=textquery&fields=formatted_address,name,geometry&key={g_key}")

    
    try:

#Get the response from the API request and capture the lat/lng data values from the request
        response = requests.get(url + parameter).json()  
        print(response)

#extract results
        home_Lat = response['candidates'][0]['geometry']['location']['lat']
        home_Lng = response['candidates'][0]['geometry']['location']['lng']
        
        results = [home[0], home[1], home_Lat, home_Lng]
        print (results)
        output.append(results)
#Generate an exception message if passenger data not found
    except Exception:
        print(f'{home} city not found. Skipping...')
print(output)

Retrieving Results for Home | Crosby, UK
{'candidates': [{'formatted_address': 'Crosby, Liverpool, UK', 'geometry': {'location': {'lat': 53.4892924, 'lng': -3.0462309}, 'viewport': {'northeast': {'lat': 53.4948136, 'lng': -3.0357799}, 'southwest': {'lat': 53.4844867, 'lng': -3.0536872}}}, 'name': 'Crosby'}], 'status': 'OK'}
['Crosby', 'Crosby, UK', 53.4892924, -3.0462309]
Retrieving Results for Home | Southsea, UK
{'candidates': [{'formatted_address': 'Southsea, Portsmouth, UK', 'geometry': {'location': {'lat': 50.783565, 'lng': -1.085559}, 'viewport': {'northeast': {'lat': 50.8031393, 'lng': -1.0287448}, 'southwest': {'lat': 50.77756120000001, 'lng': -1.1036241}}}, 'name': 'Southsea'}], 'status': 'OK'}
['Southsea', 'Southsea, UK', 50.783565, -1.085559]
Retrieving Results for Home | Soberton, Hampshire
{'candidates': [{'formatted_address': 'Soberton, Southampton, UK', 'geometry': {'location': {'lat': 50.9483849, 'lng': -1.1296041}, 'viewport': {'northeast': {'lat': 50.9580202, 'lng': -1.1262974}, 'southwest': {'lat': 50.94364419999999, 'lng': -1.1348858}}}, 'name': 'Soberton'}], 'status': 'OK'}
['Soberton, Hampshire', 'Soberton, Hampshire', 50.9483849, -1.1296041]
Retrieving Results for Home | East Cowes, UK
{'candidates': [{'formatted_address': 'East Cowes, UK', 'geometry': {'location': {'lat': 50.759108, 'lng': -1.285492}, 'viewport': {'northeast': {'lat': 50.7670946, 'lng': -1.2433702}, 'southwest': {'lat': 50.74082809999999, 'lng': -1.2934553}}}, 'name': 'East Cowes'}], 'status': 'OK'}
['East Cowes', 'East Cowes, UK', 50.759108, -1.285492]
Retrieving Results for Home | Clones, UK
{'candidates': [{'formatted_address': '78 Meon Rd, Southsea, Portsmouth, Southsea PO4 8NN, United Kingdom', 'geometry': {'location': {'lat': 50.7956346, 'lng': -1.0556913}, 'viewport': {'northeast': {'lat': 50.79702977989273, 'lng': -1.054353370107278}, 'southwest': {'lat': 50.79433012010728, 'lng': -1.057053029892722}}}, 'name': 'Clones UK'}, {'formatted_address': 'Portsmouth enterprise centre, Quartremaine Rd, Portsmouth PO3 5QT, United Kingdom', 'geometry': {'location': {'lat': 50.82283409999999, 'lng': -1.052706}, 'viewport': {'northeast': {'lat': 50.82406677989272, 'lng': -1.051842120107278}, 'southwest': {'lat': 50.82136712010728, 'lng': -1.054541779892722}}}, 'name': 'Clones UK'}], 'status': 'OK'}
['Clones', 'Clones, UK', 50.7956346, -1.0556913]
Retrieving Results for Home | Rue National-Ambroise, France
{'candidates': [{'formatted_address': '14 Rue nationale, 37400 Amboise, France', 'geometry': {'location': {'lat': 47.41249999999999, 'lng': 0.9838889}, 'viewport': {'northeast': {'lat': 47.41372977989272, 'lng': 0.9851429798927221}, 'southwest': {'lat': 47.41103012010728, 'lng': 0.982443320107278}}}, 'name': 'Le Patio'}], 'status': 'OK'}
['Rue National-Ambroise, France', 'Rue National-Ambroise, France', 47.41249999999999, 0.9838889]
Retrieving Results for Home | Lewisham, UK
{'candidates': [{'formatted_address': 'London Borough of Lewisham, UK', 'geometry': {'location': {'lat': 51.4414579, 'lng': -0.0117006}, 'viewport': {'northeast': {'lat': 51.4935635, 'lng': 0.0390452}, 'southwest': {'lat': 51.41355, 'lng': -0.0750933}}}, 'name': 'London Borough of Lewisham'}], 'status': 'OK'}
['Lewisham', 'Lewisham, UK', 51.4414579, -0.0117006]
Retrieving Results for Home | Hull, UK
{'candidates': [{'formatted_address': 'Hull, UK', 'geometry': {'location': {'lat': 53.76762360000001, 'lng': -0.3274198}, 'viewport': {'northeast': {'lat': 53.8132502, 'lng': -0.2413964}, 'southwest': {'lat': 53.71949129999999, 'lng': -0.4225751}}}, 'name': 'Hull'}], 'status': 'OK'}
['Hull', 'Hull, UK', 53.76762360000001, -0.3274198]
Retrieving Results for Home | Wokingham, UK
{'candidates': [{'formatted_address': 'Wokingham, UK', 'geometry': {'location': {'lat': 51.410457, 'lng': -0.833861}, 'viewport': {'northeast': {'lat': 51.4298057, 'lng': -0.7925223}, 'southwest': {'lat': 51.3866601, 'lng': -0.8765881}}}, 'name': 'Wokingham'}], 'status': 'OK'}
['Wokingham', 'Wokingham, UK', 51.410457, -0.833861]
Retrieving Results for Home | Belfast, UK
{'candidates': [{'formatted_address': 'Belfast, UK', 'geometry': {'location': {'lat': 54.59728500000001, 'lng': -5.93012}, 'viewport': {'northeast': {'lat': 54.65920999999999, 'lng': -5.808004599999999}, 'southwest': {'lat': 54.53055, 'lng': -6.04526}}}, 'name': 'Belfast'}], 'status': 'OK'}
['Belfast', 'Belfast, UK', 54.59728500000001, -5.93012]
Retrieving Results for Home | Bitterne Park, Southampton
{'candidates': [{'formatted_address': 'Bitterne Park, Southampton, UK', 'geometry': {'location': {'lat': 50.9286985, 'lng': -1.3721383}, 'viewport': {'northeast': {'lat': 50.9330842, 'lng': -1.3664317}, 'southwest': {'lat': 50.92105369999999, 'lng': -1.3800385}}}, 'name': 'Bitterne Park'}], 'status': 'OK'}
['Bitterne Park, Southampton', 'Bitterne Park, Southampton', 50.9286985, -1.3721383]
Retrieving Results for Home | Bournemouth, UK
{'candidates': [{'formatted_address': 'Bournemouth, UK', 'geometry': {'location': {'lat': 50.719164, 'lng': -1.880769}, 'viewport': {'northeast': {'lat': 50.7988916, 'lng': -1.7406581}, 'southwest': {'lat': 50.7091165, 'lng': -1.9788195}}}, 'name': 'Bournemouth'}], 'status': 'OK'}
['Bournemouth', 'Bournemouth, UK', 50.719164, -1.880769]
Retrieving Results for Home | Shortland, Kent
{'candidates': [{'formatted_address': 'Shortlands, Bromley, UK', 'geometry': {'location': {'lat': 51.4060266, 'lng': 0.0014606}, 'viewport': {'northeast': {'lat': 51.4096116, 'lng': 0.0077992}, 'southwest': {'lat': 51.4040086, 'lng': -0.0067973}}}, 'name': 'Shortlands'}], 'status': 'OK'}
['Shortland, Kent', 'Shortland, Kent', 51.4060266, 0.0014606]
Retrieving Results for Home | Woolston, Hampshire
{'candidates': [{'formatted_address': 'Woolston, Southampton, UK', 'geometry': {'location': {'lat': 50.8935081, 'lng': -1.3748443}, 'viewport': {'northeast': {'lat': 50.8991888, 'lng': -1.3609911}, 'southwest': {'lat': 50.8900975, 'lng': -1.384591}}}, 'name': 'Woolston'}], 'status': 'OK'}
['Woolston, Hampshire', 'Woolston, Hampshire', 50.8935081, -1.3748443]
Retrieving Results for Home | Stirling, UK
{'candidates': [{'formatted_address': 'Stirling, UK', 'geometry': {'location': {'lat': 56.1165227, 'lng': -3.9369029}, 'viewport': {'northeast': {'lat': 56.1455382, 'lng': -3.9043966}, 'southwest': {'lat': 56.0918724, 'lng': -3.9750002}}}, 'name': 'Stirling'}], 'status': 'OK'}
['Stirling', 'Stirling, UK', 56.1165227, -3.9369029]
Retrieving Results for Home | Sholing, Hampshire
{'candidates': [{'formatted_address': 'Sholing, Southampton, UK', 'geometry': {'location': {'lat': 50.8977373, 'lng': -1.3470149}, 'viewport': {'northeast': {'lat': 50.910123, 'lng': -1.327243}, 'southwest': {'lat': 50.892788, 'lng': -1.3652658}}}, 'name': 'Sholing'}], 'status': 'OK'}
['Sholing, Hampshire', 'Sholing, Hampshire', 50.8977373, -1.3470149]
Retrieving Results for Home | Portsmouth, UK
{'candidates': [{'formatted_address': 'Portsmouth, UK', 'geometry': {'location': {'lat': 50.8197675, 'lng': -1.0879769}, 'viewport': {'northeast': {'lat': 50.8593091, 'lng': -1.0184922}, 'southwest': {'lat': 50.7501624, 'lng': -1.1749682}}}, 'name': 'Portsmouth'}], 'status': 'OK'}
['Portsmouth', 'Portsmouth, UK', 50.8197675, -1.0879769]
Retrieving Results for Home | Southport, UK
{'candidates': [{'formatted_address': 'Southport, UK', 'geometry': {'location': {'lat': 53.645708, 'lng': -3.010113}, 'viewport': {'northeast': {'lat': 53.6832362, 'lng': -2.9384968}, 'southwest': {'lat': 53.58507909999999, 'lng': -3.0658924}}}, 'name': 'Southport'}], 'status': 'OK'}
['Southport', 'Southport, UK', 53.645708, -3.010113]
Retrieving Results for Home | Reading, UK
{'candidates': [{'formatted_address': 'Reading, UK', 'geometry': {'location': {'lat': 51.4542645, 'lng': -0.9781303}, 'viewport': {'northeast': {'lat': 51.4931339, 'lng': -0.9284944}, 'southwest': {'lat': 51.4097795, 'lng': -1.0636011}}}, 'name': 'Reading'}], 'status': 'OK'}
['Reading', 'Reading, UK', 51.4542645, -0.9781303]
Retrieving Results for Home | New Southgate, UK
{'candidates': [{'formatted_address': 'New Southgate, London N11 2NA, UK', 'geometry': {'location': {'lat': 51.61100099999999, 'lng': -0.135469}, 'viewport': {'northeast': {'lat': 51.6179296, 'lng': -0.1194616}, 'southwest': {'lat': 51.6040714, 'lng': -0.1514764}}}, 'name': 'New Southgate'}], 'status': 'OK'}
['New Southgate', 'New Southgate, UK', 51.61100099999999, -0.135469]
Retrieving Results for Home | Northam, UK
{'candidates': [{'formatted_address': 'Northam, UK', 'geometry': {'location': {'lat': 51.039809, 'lng': -4.213152}, 'viewport': {'northeast': {'lat': 51.07881279999999, 'lng': -4.1874826}, 'southwest': {'lat': 51.0231363, 'lng': -4.2413759}}}, 'name': 'Northam'}], 'status': 'OK'}
['Northam', 'Northam, UK', 51.039809, -4.213152]
Retrieving Results for Home | Gosport, UK
{'candidates': [{'formatted_address': 'Gosport, UK', 'geometry': {'location': {'lat': 50.794995, 'lng': -1.117547}, 'viewport': {'northeast': {'lat': 50.8402559, 'lng': -1.1119148}, 'southwest': {'lat': 50.77329109999999, 'lng': -1.1892455}}}, 'name': 'Gosport'}], 'status': 'OK'}
['Gosport', 'Gosport, UK', 50.794995, -1.117547]
Retrieving Results for Home | Dublin, Ireland
{'candidates': [{'formatted_address': 'Dublin, Ireland', 'geometry': {'location': {'lat': 53.3498053, 'lng': -6.2603097}, 'viewport': {'northeast': {'lat': 53.42521010000001, 'lng': -6.0439235}, 'southwest': {'lat': 53.22343009999999, 'lng': -6.4474847}}}, 'name': 'Dublin'}], 'status': 'OK'}
['Dublin, Ireland', 'Dublin, Ireland', 53.3498053, -6.2603097]
Retrieving Results for Home | Plymouth, UK
{'candidates': [{'formatted_address': 'Plymouth, UK', 'geometry': {'location': {'lat': 50.3754565, 'lng': -4.1426565}, 'viewport': {'northeast': {'lat': 50.4441664, 'lng': -4.0196074}, 'southwest': {'lat': 50.332722, 'lng': -4.205532499999999}}}, 'name': 'Plymouth'}], 'status': 'OK'}
['Plymouth', 'Plymouth, UK', 50.3754565, -4.1426565]
Retrieving Results for Home | Bridgwood, UK
{'candidates': [{'formatted_address': 'Bridgeworks, Ferry Road, Hessle HU13 0TP, United Kingdom', 'geometry': {'location': {'lat': 53.719356, 'lng': -0.433128}, 'viewport': {'northeast': {'lat': 53.72072572989272, 'lng': -0.4317386201072778}, 'southwest': {'lat': 53.71802607010728, 'lng': -0.4344382798927223}}}, 'name': 'Bridgewood (UK)'}], 'status': 'OK'}
['Bridgwood', 'Bridgwood, UK', 53.719356, -0.433128]
Retrieving Results for Home | Sandown, UK
{'candidates': [{'formatted_address': 'Sandown, UK', 'geometry': {'location': {'lat': 50.6607588, 'lng': -1.1488128}, 'viewport': {'northeast': {'lat': 50.6731783, 'lng': -1.1077467}, 'southwest': {'lat': 50.64933990000001, 'lng': -1.1761492}}}, 'name': 'Sandown'}], 'status': 'OK'}
['Sandown', 'Sandown, UK', 50.6607588, -1.1488128]
Retrieving Results for Home | Grimsby, UK
{'candidates': [{'formatted_address': 'Grimsby, UK', 'geometry': {'location': {'lat': 53.567471, 'lng': -0.080784}, 'viewport': {'northeast': {'lat': 53.5940665, 'lng': -0.0405235}, 'southwest': {'lat': 53.5250206, 'lng': -0.1502886}}}, 'name': 'Grimsby'}], 'status': 'OK'}
['Grimsby', 'Grimsby, UK', 53.567471, -0.080784]
Retrieving Results for Home | Little Sutton, Cheshire
{'candidates': [{'formatted_address': 'Little Sutton, Ellesmere Port, UK', 'geometry': {'location': {'lat': 53.285023, 'lng': -2.9443229}, 'viewport': {'northeast': {'lat': 53.2919282, 'lng': -2.929668}, 'southwest': {'lat': 53.2744976, 'lng': -2.9693225}}}, 'name': 'Little Sutton'}], 'status': 'OK'}
['Little Sutton, Cheshire', 'Little Sutton, Cheshire', 53.285023, -2.9443229]
Retrieving Results for Home | Totton, Hampshire
{'candidates': [{'formatted_address': 'Totton and Eling, UK', 'geometry': {'location': {'lat': 50.9141239, 'lng': -1.4985934}, 'viewport': {'northeast': {'lat': 50.9388253, 'lng': -1.4588048}, 'southwest': {'lat': 50.8922276, 'lng': -1.5256442}}}, 'name': 'Totton and Eling'}], 'status': 'OK'}
['Totton, Hampshire', 'Totton, Hampshire', 50.9141239, -1.4985934]
Retrieving Results for Home | Pournemouth, UK
{'candidates': [{'formatted_address': 'Bournemouth, UK', 'geometry': {'location': {'lat': 50.719164, 'lng': -1.880769}, 'viewport': {'northeast': {'lat': 50.7988916, 'lng': -1.7406581}, 'southwest': {'lat': 50.7091165, 'lng': -1.9788195}}}, 'name': 'Bournemouth'}], 'status': 'OK'}
['Pournemouth', 'Pournemouth, UK', 50.719164, -1.880769]
Retrieving Results for Home | Ryde, Isle of Wight
{'candidates': [{'formatted_address': 'Ryde, UK', 'geometry': {'location': {'lat': 50.729952, 'lng': -1.163282}, 'viewport': {'northeast': {'lat': 50.734116, 'lng': -1.1209769}, 'southwest': {'lat': 50.704519, 'lng': -1.2076529}}}, 'name': 'Ryde'}], 'status': 'OK'}
['Ryde, Isle of Wight', 'Ryde, Isle of Wight', 50.729952, -1.163282]
Retrieving Results for Home | Rockbourne, UK
{'candidates': [{'formatted_address': 'Rockbourne, Fordingbridge, UK', 'geometry': {'location': {'lat': 50.9625534, 'lng': -1.8385303}, 'viewport': {'northeast': {'lat': 50.9662656, 'lng': -1.8347062}, 'southwest': {'lat': 50.95757099999999, 'lng': -1.8460035}}}, 'name': 'Rockbourne'}], 'status': 'OK'}
['Rockbourne', 'Rockbourne, UK', 50.9625534, -1.8385303]
Retrieving Results for Home | Liverpool, UK
{'candidates': [{'formatted_address': 'Liverpool, UK', 'geometry': {'location': {'lat': 53.4083714, 'lng': -2.9915726}, 'viewport': {'northeast': {'lat': 53.503907, 'lng': -2.8129382}, 'southwest': {'lat': 53.3204478, 'lng': -3.0191793}}}, 'name': 'Liverpool'}], 'status': 'OK'}
['Liverpool', 'Liverpool, UK', 53.4083714, -2.9915726]
Retrieving Results for Home | Romsey, UK
{'candidates': [{'formatted_address': 'Romsey, UK', 'geometry': {'location': {'lat': 50.98893, 'lng': -1.49658}, 'viewport': {'northeast': {'lat': 51.0051004, 'lng': -1.4546493}, 'southwest': {'lat': 50.980326, 'lng': -1.5110557}}}, 'name': 'Romsey'}], 'status': 'OK'}
['Romsey', 'Romsey, UK', 50.98893, -1.49658]
Retrieving Results for Home | Woodside, Lymington
{'candidates': [{'formatted_address': 'Woodside, Lymington SO41 8AB, UK', 'geometry': {'location': {'lat': 50.74571700000001, 'lng': -1.546645}, 'viewport': {'northeast': {'lat': 50.7527768, 'lng': -1.5306376}, 'southwest': {'lat': 50.7386561, 'lng': -1.5626524}}}, 'name': 'Woodside'}], 'status': 'OK'}
['Woodside, Lymington', 'Woodside, Lymington', 50.74571700000001, -1.546645]
Retrieving Results for Home | Newport, Isle of Wight
{'candidates': [{'formatted_address': 'Newport, UK', 'geometry': {'location': {'lat': 50.700803, 'lng': -1.291633}, 'viewport': {'northeast': {'lat': 50.7297245, 'lng': -1.2621475}, 'southwest': {'lat': 50.6796234, 'lng': -1.3331688}}}, 'name': 'Newport'}], 'status': 'OK'}
['Newport, Isle of Wight', 'Newport, Isle of Wight', 50.700803, -1.291633]
Retrieving Results for Home | Headbourne, W. F.
{'candidates': [{'formatted_address': 'Walworth Business Park, South Way, Andover SP10 5AF, United Kingdom', 'geometry': {'location': {'lat': 51.21443980000001, 'lng': -1.4530102}, 'viewport': {'northeast': {'lat': 51.21574712989273, 'lng': -1.451613470107278}, 'southwest': {'lat': 51.21304747010728, 'lng': -1.454313129892722}}}, 'name': 'WF Supplies'}], 'status': 'OK'}
['Headbourne, W. F.', 'Headbourne, W. F.', 51.21443980000001, -1.4530102]
Retrieving Results for Home | Northam, Hampshire
{'candidates': [{'formatted_address': 'Northam, Southampton, UK', 'geometry': {'location': {'lat': 50.9109442, 'lng': -1.3867764}, 'viewport': {'northeast': {'lat': 50.9125624, 'lng': -1.3829525}, 'southwest': {'lat': 50.9092316, 'lng': -1.3922446}}}, 'name': 'Northam'}], 'status': 'OK'}
['Northam, Hampshire', 'Northam, Hampshire', 50.9109442, -1.3867764]
Retrieving Results for Home | Notts, UK
{'candidates': [{'formatted_address': 'Nottinghamshire, UK', 'geometry': {'location': {'lat': 53.100319, 'lng': -0.9936305999999998}, 'viewport': {'northeast': {'lat': 53.502478, 'lng': -0.6662629999999999}, 'southwest': {'lat': 52.7893914, 'lng': -1.3445929}}}, 'name': 'Nottinghamshire'}], 'status': 'OK'}
['Notts', 'Notts, UK', 53.100319, -0.9936305999999998]
Retrieving Results for Home | Winchester, UK
{'candidates': [{'formatted_address': 'Winchester, UK', 'geometry': {'location': {'lat': 51.059771, 'lng': -1.310142}, 'viewport': {'northeast': {'lat': 51.0931018, 'lng': -1.2801654}, 'southwest': {'lat': 51.0351854, 'lng': -1.3614179}}}, 'name': 'Winchester'}], 'status': 'OK'}
['Winchester', 'Winchester, UK', 51.059771, -1.310142]
Retrieving Results for Home | Somerset, UK
{'candidates': [{'formatted_address': 'Somerset, UK', 'geometry': {'location': {'lat': 51.105097, 'lng': -2.9262307}, 'viewport': {'northeast': {'lat': 51.3330028, 'lng': -2.2444341}, 'southwest': {'lat': 50.8208396, 'lng': -3.839803}}}, 'name': 'Somerset'}], 'status': 'OK'}
['Somerset', 'Somerset, UK', 51.105097, -2.9262307]
Retrieving Results for Home | London, UK
{'candidates': [{'formatted_address': 'London, UK', 'geometry': {'location': {'lat': 51.5073509, 'lng': -0.1277583}, 'viewport': {'northeast': {'lat': 51.6723432, 'lng': 0.148271}, 'southwest': {'lat': 51.38494009999999, 'lng': -0.3514683}}}, 'name': 'London'}], 'status': 'OK'}
['London', 'London, UK', 51.5073509, -0.1277583]
Retrieving Results for Home | Port Isaac, Cornwall
{'candidates': [{'formatted_address': 'Port Isaac, UK', 'geometry': {'location': {'lat': 50.59382000000001, 'lng': -4.829978}, 'viewport': {'northeast': {'lat': 50.59626, 'lng': -4.8215873}, 'southwest': {'lat': 50.585802, 'lng': -4.8367819}}}, 'name': 'Port Isaac'}], 'status': 'OK'}
['Port Isaac, Cornwall', 'Port Isaac, Cornwall', 50.59382000000001, -4.829978]
Retrieving Results for Home | Harbor View, UK
{'candidates': [{'formatted_address': '65 King St, Brixham TQ5 9TH, United Kingdom', 'geometry': {'location': {'lat': 50.3964077, 'lng': -3.5107004}, 'viewport': {'northeast': {'lat': 50.39778012989272, 'lng': -3.509387770107277}, 'southwest': {'lat': 50.39508047010728, 'lng': -3.512087429892722}}}, 'name': 'Harbour View Hotel'}], 'status': 'OK'}
['Harbor View', 'Harbor View, UK', 50.3964077, -3.5107004]
Retrieving Results for Home | Landport, UK
{'candidates': [{'formatted_address': 'Landport, Portsmouth, UK', 'geometry': {'location': {'lat': 50.8129544, 'lng': -1.0866155}, 'viewport': {'northeast': {'lat': 50.81453137989272, 'lng': -1.0850641}, 'southwest': {'lat': 50.81183172010728, 'lng': -1.0882674}}}, 'name': 'Landport'}], 'status': 'OK'}
['Landport', 'Landport, UK', 50.8129544, -1.0866155]
Retrieving Results for Home | Redland, Bristol
{'candidates': [{'formatted_address': 'Redland, Bristol, UK', 'geometry': {'location': {'lat': 51.4677204, 'lng': -2.6062403}, 'viewport': {'northeast': {'lat': 51.47856650000001, 'lng': -2.593241}, 'southwest': {'lat': 51.46080019999999, 'lng': -2.6159402}}}, 'name': 'Redland'}], 'status': 'OK'}
['Redland, Bristol', 'Redland, Bristol', 51.4677204, -2.6062403]
Retrieving Results for Home | Birkenhead, UK
{'candidates': [{'formatted_address': 'Birkenhead, UK', 'geometry': {'location': {'lat': 53.38999099999999, 'lng': -3.023009}, 'viewport': {'northeast': {'lat': 53.4117647, 'lng': -2.928625}, 'southwest': {'lat': 53.29773280000001, 'lng': -3.173881}}}, 'name': 'Birkenhead'}], 'status': 'OK'}
['Birkenhead', 'Birkenhead, UK', 53.38999099999999, -3.023009]
Retrieving Results for Home | Paddington, UK
{'candidates': [{'formatted_address': 'Paddington, London, UK', 'geometry': {'location': {'lat': 51.515973, 'lng': -0.174943}, 'viewport': {'northeast': {'lat': 51.52098230000001, 'lng': -0.1674588}, 'southwest': {'lat': 51.5121748, 'lng': -0.1833291}}}, 'name': 'Paddington'}], 'status': 'OK'}
['Paddington', 'Paddington, UK', 51.515973, -0.174943]
Retrieving Results for Home | Bowerthalk, Salisbury
{'candidates': [], 'status': 'ZERO_RESULTS'}
['Bowerthalk, Salisbury', 'Bowerthalk, Salisbury'] city not found. Skipping...
Retrieving Results for Home | Southampton, UK

In [14]:
for hometown in output:
    town = hometown[0]
    lat = hometown[2]
    lng = hometown[3]
    
    for row in input_data.index:
        home = input_data.at[row, 'Hometown']
    
        if town == home:
            
           input_data.at[row, 'Home_Lat'] = lat
           input_data.at[row, 'Home_Lng'] = lng
        
input_data

,Pclass,Name,Survived,Sex,Age,Hometown,Role,Role Additional info,Image,Misc Information,Lifeboat,Body Disposition,Job Area,Source of info 1,Source of info 2,Home_Lat,Home_Lng
0,NaN,"Anderson, J.",1.0,male,40.0,Southampton,Able bodied seaman,NaN,NaN,NaN,NaN,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN,50.9097,-1.404351
1,NaN,"Archer, Ernest",1.0,male,36.0,Southampton,Able bodied seaman,NaN,NaN,NaN,16,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN,50.9097,-1.404351
2,NaN,"Bradley, F.",0.0,male,29.0,Southampton,Able bodied seaman,NaN,NaN,NaN,NaN,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN,50.9097,-1.404351
3,NaN,"Brice, W.",1.0,male,42.0,Southampton,Able bodied seaman,NaN,NaN,NaN,11,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN,50.9097,-1.404351
4,NaN,"Buley, Edward J.",1.0,male,27.0,Southampton,Able bodied seaman,NaN,NaN,NaN,10,NaN,Deck Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN,50.9097,-1.404351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
914,NaN,"Williams, Jack",0.0,male,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine Department,https://www.lva.virginia.gov/exhibits/titanic/...,NaN,NaN,NaN

In [15]:
input_data.to_csv('data/CrewData_LatLong.csv')        
print(input_data)

     Pclass              Name  Survived   Sex   Age     Hometown  \
0       NaN      Anderson, J.       1.0  male  40.0  Southampton
1       NaN    Archer, Ernest       1.0  male  36.0  Southampton
2       NaN       Bradley, F.       0.0  male  29.0  Southampton
3       NaN         Brice, W.       1.0  male  42.0  Southampton
4       NaN  Buley, Edward J.       1.0  male  27.0  Southampton
..      ...               ...       ...   ...   ...          ...
910     NaN               NaN       NaN   NaN   NaN          NaN
911     NaN               NaN       NaN   NaN   NaN          NaN
912     NaN               NaN       NaN   NaN   NaN          NaN
913     NaN               NaN       NaN   NaN   NaN          NaN
914     NaN    Williams, Jack       0.0  male  28.0          NaN

                   Role Role Additional info Image Misc Information Lifeboat  \
0    Able bodied seaman                  NaN   NaN              NaN      NaN
1    Able bodied seaman                  NaN   NaN              NaN       16
2    Able bodied seaman                  NaN   NaN              NaN      NaN
3    Able bodied seaman                  NaN   NaN              NaN       11
4    Able bodied seaman                  NaN   NaN              NaN       10
..                  ...                  ...   ...              ...      ...
910                 NaN                  NaN   NaN              NaN      NaN
911                 NaN                  NaN   NaN              NaN      NaN
912                 NaN                  NaN   NaN              NaN      NaN
913                 NaN                  NaN   NaN              NaN      NaN
914                 NaN                  NaN   NaN              NaN      NaN

    Body Disposition           Job Area  \
0                NaN    Deck Department
1                NaN    Deck Department
2                NaN    Deck Department
3                NaN    Deck Department
4                NaN    Deck Department
..               ...                ...
910              NaN                NaN
911              NaN                NaN
912              NaN                NaN
913              NaN                NaN
914              NaN  Engine Department

                                      Source of info 1 Source of info 2  \
0    https://www.lva.virginia.gov/exhibits/titanic/...              NaN
1    https://www.lva.virginia.gov/exhibits/titanic/...              NaN
2    https://www.lva.virginia.gov/exhibits/titanic/...              NaN
3    https://www.lva.virginia.gov/exhibits/titanic/...              NaN
4    https://www.lva.virginia.gov/exhibits/titanic/...              NaN
..                                                 ...              ...
910                                                NaN              NaN
911                                                NaN              NaN
912                                                NaN              NaN
913                                                NaN              NaN
914  https://www.lva.virginia.gov/exhibits/titanic/...              NaN

     Home_Lat  Home_Lng
0     50.9097 -1.404351
1     50.9097 -1.404351
2     50.9097 -1.404351
3     50.9097 -1.404351
4     50.9097 -1.404351
..        ...       ...
910       NaN       NaN
911       NaN       NaN
912       NaN       NaN
913       NaN       NaN
914       NaN       NaN

[915 rows x 17 columns]